# Change these first
owner: VenturiHealthSystems
repo: status
sites:
  - name: VenturiHealthSystems
    url: https://dataisQ.replit.app
  - name: API Health
    url: https://dataisQ.replit.app/api/v1/health
    expectedStatusCodes:
      - 200
status-website:
  name: Venturi Health Systems Status
  logoUrl: https://dataisQ.replit.app.replit.app/favicon.ico
  theme: light
i18n:
  footer: "© 2025 Venturi Health Systems Ltd."
